[package]
name = "upt"
version = "0.1.0"
edition = "2024"
description = "Unified Perl Tool"
repository = "https://github.com/uperl/upt"
license = "MIT"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4", features = ["derive"] }
comfy-table = "7"
dirs = "6"
hex = "0.4"
metacpan-api-modern = { git = "https://github.com/uperl/rust-metacpan-api-modern", tag = "v0.3.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
toml = "0.8"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
] }


[package.metadata.deb]
maintainer = "Nobody <devnull@wdlabs.com>"
copyright = "Nobody"
extended-description = """\
Unified Perl Tool"""
section = "utils"
priority = "optional"
assets = [
    ["target/release/upt", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/upt/README.md", "644"],
    ["LICENSE", "usr/share/doc/upt/LICENSE", "644"],
]

